name: Flask CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest requests

      - name: Ejecutar pruebas unitarias (pytest)
        run: pytest || echo "Sin pruebas unitarias definidas"

      - name: Levantar servidor Flask en background
        run: |
          nohup python app.py &
          sleep 5  # espera a que arranque

      - name: Probar endpoint raíz
        run: |
          curl -f http://127.0.0.1:5000/ || exit 1

